name: CI
permissions: write-all

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.61
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - name: Kafka KRaft
        uses: spicyparrot/kafka-kraft-action@v1.1.3
        with:
          kafka-version: "3.7.0"
          kafka-topics: "test_topic,3,test_topic_2,3"
      - name: Test
        run: go test --tags=integration_test -v -race ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
        env:
            KAFKA_BOOTSTRAP_SERVERS: ${{ env.kafka_runner_address }}:9093
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges 


    
